-- phase: expand
-- OpenVibe.Help's per-ticket conversation (capability chat.ticket.write,
-- chat.ticket-conversation@1, added in openvibe-contracts 0.100.0). One conversation per
-- (ticket id, calling service); two services on one ticket get two conversations and neither
-- can read the other's. Messages carry the author's kind, subject and body (plain text, never
-- HTML) and the author's own created_at; Chat orders by its own id (recorded_at is when it
-- arrived). Service tokens are loopback-only and never granted to an app or an agent.
CREATE TABLE IF NOT EXISTS ticket_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" NOT NULL DEFAULT ov_now(),
    UNIQUE (ticket_id, service)
);
CREATE TABLE IF NOT EXISTS ticket_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES ticket_conversations(id) ON DELETE CASCADE,
    author_kind text COLLATE "C" NOT NULL CHECK (author_kind IN ('person', 'agent', 'staff')),
    author text COLLATE "C" NOT NULL,
    body text COLLATE "C" NOT NULL,               -- the author's text, as sent; Chat never renders it
    created_at text COLLATE "C" NOT NULL,          -- the author's clock (contract), not Chat's ordering
    recorded_at text COLLATE "C" NOT NULL DEFAULT ov_now()
);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_conversation ON ticket_messages(conversation_id, id);
